### ISSUE TITLE
Integrate coala

### ISSUE THREAD

**Issue by hemangsk** [rahulcode22/Hackerrank#6]
- Add PEP8BEar
- PyLintBear
- Indentation Bear

**Comment by hemangsk** [comment]
You can find more bears on coala.io/languages 😃  👍

**Comment by hemangsk** [comment]
or let me do that for you! 😃

**Comment by hemangsk** [comment]
@gh-node-proto-bot ! Get us our coafile!

**Comment by hemangsk** [comment]
@gh-node-proto-bot ! Get us our coafile!

**Comment by hemangsk** [comment]
Oh, okay Let me make a PR as well @coafile

**Comment by coafile** [comment]
Greetings! I'm the coafile bot and I'm here to get your coafile ready. Sit Tight!

**Comment by hemangsk** [comment]
☕️

**Comment by coafile** [comment]
```# Generated by coala-quickstart on 28 Jun 2017.
[default]
bears = InvalidLinkBear, FilenameBear
files = **.py, **.md, **.cpp, **.c
[c]
bears = GNUIndentBear, ClangComplexityBear, CSecurityBear
files = **.c
[python]
bears = PycodestyleBear
files = **.py
[markdown]
bears = MarkdownBear, coalaBear, LineLengthBear, LicenseCheckBear, DuplicateFileBear
files = **.md
[c++]
bears = GNUIndentBear, CPPCheckBear, CPPCleanBear, ClangComplexityBear
files = **.cpp
```

**Comment by coafile** [comment]
Oops! Looks like I've already made a coafile PR!

**Comment by coafile** [comment]
coafile creation process Successful! :tada: :tada: :tada:


 Next Steps: 

 Step 1: Merge the Pull Request https://github.com/rahulcode22/Hackerrank/pull/7 having the .coafile.
 Step 2: Turn on GitMate Integration on this repository.
 Step 3: Turn on code analysis for automated code reviews on your PRs

 Happy Linting! :tada:

**Comment by coafile** [comment]
Greetings! I'm the coafile bot and I'm here to get your coafile ready. Sit Tight!

**Comment by coafile** [comment]
Greetings! I'm the coafile bot and I'm here to get your coafile ready. Sit Tight!

**Comment by coafile** [comment]
```# Generated by coala-quickstart on 28 Jun 2017.
[default]
bears = FilenameBear, InvalidLinkBear
files = **.c, **.md, **.cpp, **.py
[python]
bears = PycodestyleBear
files = **.py
[c]
bears = ClangComplexityBear, CSecurityBear, GNUIndentBear
files = **.c
[markdown]
bears = DuplicateFileBear, LicenseCheckBear, LineLengthBear, MarkdownBear, coalaBear
files = **.md
[c++]
bears = ClangComplexityBear, GNUIndentBear, CPPCleanBear, CPPCheckBear
files = **.cpp
```

**Comment by coafile** [comment]
Oops! Looks like there was some problem making the coafile PR! Retrying...

**Comment by coafile** [comment]
Oops! Looks like I've already made a coafile PR!
